### ISSUE TITLE
Addition of `#![warn(clippy::nursery, clippy::pedantic)]`.

### ISSUE THREAD

**Issue by Xithrius** [Piturnah/gex#15]
Hello!

Adding the following snippet to the top of `main.rs` will introduce a bunch of best practices and such that can improve code quality. See [here](https://doc.rust-lang.org/stable/clippy/) for more details.

```rs
#![warn(clippy::nursery, clippy::pedantic)]
```

[This](https://github.com/Xithrius/twitch-tui/blob/main/src/main.rs#L2-L11) is the allow list that I have, also as a suggestion.

Happy holidays!

**Comment by Piturnah** [comment]
Thanks for the suggestion and happy holidays!

**Comment by Xithrius** [comment]
❤️
