### ISSUE TITLE
Doesn't know its in git repo in child directories

### ISSUE THREAD

**Issue by praveenperera** [Piturnah/gex#2]
If I'm in a child directory of a git repo it should recognize that I am in a git repo.

Since you are already using the `git` command you could use `git rev-parse --is-inside-work-tree` to detect a git repo instead of looking for the git folder

**Comment by Piturnah** [comment]
Thank you for pointing this out. I'll implement this fix for now, but in future this will likely be done using [git2-rs](https://github.com/rust-lang/git2-rs) as per discussions in this [Reddit thread](https://www.reddit.com/r/rust/comments/wpqeqj/comment/ikiat25/?utm_source=share&utm_medium=web2x&context=3)

**Comment by Piturnah** [comment]
Fixed in 0.3 :tada:
