### ISSUE TITLE
[Feature]: configure whitespace error highlighting

### ISSUE THREAD

**Issue by evanrichter** [Piturnah/gex#45]
## Description

`git diff` on the terminal highlights incorrect whitespace in the terminal. Example:

![image](https://github.com/Piturnah/gex/assets/330292/180b0548-161f-4b01-a389-aa2306557ad1)

But in gex (tested with 0.5.0 using `nix run nixpkgs#gex`), this whitespace error isn't shown:

![image](https://github.com/Piturnah/gex/assets/330292/9a3a1ce0-7dd6-4c99-bebd-7151a85ed228)

## Additional Information

The git diff flag to use is `--ws-error-highlight`, and I think an appropriate value would be `new`.

### wait, should this actually be a bug report?

It seems like running the git command doesn't read my user level git config either, for some reason, even when I set `diff.wsErrorHighlight = new`

**Comment by evanrichter** [comment]
> when you referred to "running the git command" ...

ah, sorry, I was just talking about the main gex output. I noticed the way the diff is generated (here, for unstaged commits) is like:

https://github.com/Piturnah/gex/blob/f71214d00b30007bed85e2a58c4ccf6310abd789/src/status.rs#L450

so my comment was about running git like this seems to ignore the config I explicitly set. The TTY detection theory makes sense

**Comment by evanrichter** [comment]
oh sweet! can't wait to try this out :D

**Comment by Piturnah** [comment]
Released in 0.6 :tada:
