### ISSUE TITLE
Add ability to back out of the "New branch" input screen without creating a new branch

### ISSUE THREAD

**Issue by LukeHalasy** [Piturnah/gex#78]
### Type of Feature

Performance Improvements

### Description

Users should be able to press "Esc" or Ctrl-C (don't know if we can override that) to be able to be backed out of the "new branch" text input screen.

**Comment by Piturnah** [comment]
This will be trivial to fix after #65. I'll make sure to do it before making the next release :)

Also, thanks for opening your PR! I'll take a look as soon as I get the chance

**Comment by Piturnah** [comment]
And fixed in 0.6.4 :tada: (sorry for the notif spam)
