### ISSUE TITLE
[Feature]: Ability to sort branch selection window by most recently accessed

### ISSUE THREAD

**Issue by LukeHalasy** [Piturnah/gex#79]
### Type of Feature

New Feature

### Description

At work, I have >300 branches within the checkout window. Most of the time I am not going to randomly checkout a branch I haven't checked out in more than a couple of months.

It would be sweet to have the ability (config option) to sort the branch selection window by recently accessed date so that it's easy to find the branch I want to checkout.

Currently I have to scroll for a while to get to the master branch to be able to check that out, pull in recent upstream changes, and then create a new branch

**Comment by Piturnah** [comment]
Thanks for the issue! Sorting by recent access sounds like a great idea, but I don't think git supports it -- meaning we'd have to store that info ourselves somewhere on the disk -- which I don't *particularly* want to do

Also, there would be the issue that if you were to checkout branches outside of gex then we wouldn't get info about that, so it's slightly awkward for the user.

I have actually already (mostly) implemented a fuzzy-search version of the branch list -- I axed it in the end as it was annoying for short branch lists, and obviously would override use of <kbd>j</kbd> and <kbd>k</kbd> for navigation

It's not sorting by recent access, but would this kind of thing solve your issue? I think we could get the best of both worlds by having this fuzzy search be toggleable.

**Comment by LukeHalasy** [comment]
You are correct that it is, sadly, not built into Git. 

However, there is an alias that you can set up to get this information -> [link to article talking about it](https://luigitesch.io/git-lb-how-to-get-the-last-branches-with-you-have-worked/).

With this alias, it wouldn't matter whether or not the branch was checked out through Git.

> Thanks for the issue! Sorting by recent access sounds like a great idea, but I don't think git supports it -- meaning we'd have to store that info ourselves somewhere on the disk -- which I don't _particularly_ want to do
> 
> Also, there would be the issue that if you were to checkout branches outside of gex then we wouldn't get info about that, so it's slightly awkward for the user.

You are correct that it is, sadly, not built into Git. 

However, there is an alias that you can set up to get this information -> [link to article talking about it](https://luigitesch.io/git-lb-how-to-get-the-last-branches-with-you-have-worked/).

With this alias, it wouldn't matter whether or not the branch was checked out through Git.

**Comment by LukeHalasy** [comment]
> I have actually already (mostly) implemented a fuzzy-search version of the branch list -- I axed it in the end as it was annoying for short branch lists, and obviously would override use of j and k for navigation
> 
> It's not sorting by recent access, but would this kind of thing solve your issue? I think we could get the best of both worlds by having this fuzzy search be toggleable.

This would be another cool feature to opt into.
Maybe within the branch list, if you type `/`, it will launch the fuzzy find version (Similar to how searching works in Vim/Helix)
