### ISSUE TITLE
[Feature]: Add the ability to open a file, using default terminal text editor (set in $EDITOR)

### ISSUE THREAD

**Issue by LukeHalasy** [Piturnah/gex#85]
### Type of Feature

New Feature

### Description

Add the ability to, when you press Enter on a file, open a file via the `gex` interface.
Don't know what this would entail.

**Comment by Piturnah** [comment]
It's an interesting idea, and this would be pretty straightforward to implement.

I do worry that it may be too much for gex to also be an "editing environment", although I can definitely also see the appeal of this, for example for quick edits to fix something about a diff.

With that in mind, another cool feature would be if you press enter on a particular hunk, it could jump your cursor to that hunk (when it's an editor that's known to support this).

Sure, I think I'm sold.

**Comment by LukeHalasy** [comment]
> I do worry that it may be too much for gex to also be an "editing environment", although I can definitely also see the appeal of this, for example for quick edits to fix something about a diff.

To clarify I do not think that any file-editing should be done through gex. Just think gex should provide the ability to open a text editor with the selected file (+hunk).

Often times when I checkout a change I am working on I only really care about the files I've already changed.
This change will pair nicely / require #41

**Comment by LukeHalasy** [comment]
> With that in mind, another cool feature would be if you press enter on a particular hunk, it could jump your cursor to that hunk (when it's an editor that's known to support this).

Couldn't agree more. Especially cool for large files. For helix this can be done with the following syntax `hx filename:row_number:column_number`

**Comment by Piturnah** [comment]
This is now implemented on main, feel free to give it a try!

**Comment by LukeHalasy** [comment]
This is awesome!  Great work.
Was a cool learning opp, because I implemented it locally before you and then was able to see the way you went about doing it.

**Comment by Piturnah** [comment]
Released in 0.6.4 :tada:
